### ISSUE TITLE
Zombify if-else/elif

### ISSUE THREAD

**Issue by sn0w** [sn0w/Undead-C#2]
Currently UDC supports:
- `if(bool) { ... }`
- `if(bool) { ... } else { ... }`
- `if(bool) { ... } elif(bool) { ... }`

I have absolutely no idea how to bring this into the zombie/apocalypse theme.
Any ideas are appreciated :)

**Comment by guay0ta** [comment]
what about 

BITE(bool) { ... }
BITE(bool) { ... } INFECT { ... }
BITE(bool) { ... } INVISIBLE { ... }

if bite yes no dead? -- if bite yes no dead? infect but not dead -- if not infected invisibly infected?

**Comment by sn0w** [comment]
`INFECT` and `INVISIBLE` are already taken 😅 

`INFECT` is used to load other modules:
```js
INFECT("module.udc") //would compile to require(...);
```

`INVISIBLE` was considered to be a replacement of the `private` keyword for classes.
See #3 for a class example.

`BITE()` is a good one though ;)

**Comment by guay0ta** [comment]
so.. 
BITE() { ... } ESCAPE { ... }
BITE() { ... } CHASE() { ... }

**Comment by sn0w** [comment]
`BITE`, `CHASE`, `ESCAPE` are now part of the definition.

#closed
